site_name: mkdocs version

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true

theme:
  name: material

plugins:
  - search
  - mkdocstrings

extra:
  version:
    provider: mike
  
nav:
  - Home: index.md
  - Content: content.md