site_name: mkdocs version

markdown_extensions:
  - pymdownx.snippets

theme:
  name: material

plugins:
  - search

extra:
  version:
    provider: mike
  
nav:
  - Home: index.md
  - Content: content.md